version: "3.7"

services:
  ubuntu_sysbox_dockerized:
    container_name: ubuntu_sysbox_dockerized
    image: kilpio/ubuntu_sysbox_dockerized:latest
    user: root
    runtime: sysbox-runc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
